
export const Content = [
    {   
        id:1,
        author:"a",
        category:"배달",
        title:"공덕 이마트 꽁치 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:3,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:2,

    },
    
    {
        id:2,
        author:"a",
        category:"온라인",
        title:"공덕 이마트 꽁치 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:5,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:2,

    },
    {
        id:3,
        author:"a",
        category:"배달",
        title:"공덕 이마트 꽁치 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:5,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:1,

    },
    {
        id:4,
        author:"a",
        category:"배달",
        title:"공덕 이마트 양파 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:5,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:1,

    },
    {
        id:5,
        author:"a",
        category:"배달",
        title:"공덕 이마트 양파 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:5,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:1,

    },
    {
        id:6,
        author:"a",
        category:"배달",
        title:"공덕 이마트 양파 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:5,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:1,

    },
    {
        id:7,
        author:"a",
        category:"오프라인",
        title:"공덕 이마트 양파 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:5,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:2,
   
    },
    {
        id:8,
        author:"a",
        category:"오프라인",
        title:"공덕 이마트 꽁치 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:3,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:2,
    
    },
    {
        id:9,
        author:"a",
        category:"오프라인",
        title:"공덕 이마트 꽁치 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:3,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:2,
  
    },
    {
        id:10,
        author:"a",
        category:"오프라인",
        title:"공덕 이마트 꽁치 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:3,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:2,
    
    },
    {
        id:11,
        author:"a",
        category:"오프라인",
        title:"공덕 이마트 꽁치 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:3,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:2,
    
    },
    {
        id:12,
        author:"a",
        category:"오프라인",
        title:"공덕 이마트 꽁치 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:3,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:2,
  
    },
    {
        id:13,
        author:"a",
        category:"오프라인",
        title:"공덕 이마트 꽁치 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:3,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:2,
   
    },
    {
        id:14,
        author:"a",
        category:"오프라인",
        title:"공덕 이마트 꽁치 같이 사실 분 구해요!",
        pub_date:"2021-11-07",
        body:"우리 둘은 얼어붙지 않을 꺼야바다 속의 모래까지 녹일 꺼야춤을 추며 절망이랑 싸울 꺼야얼어 붙은 아스팔트 도시 위로너와 나의 세대가 마지막이면 어떡해또 다른 빙하기가 찾아오면 어떡해긴 세월에 변하지 않을 그런 사랑은 없겠지만그 사랑을 기다려줄 그런 사람을 찾는 거야",
        region: "마포구 공덕동",
        item:"스니커즈",
        limit:3,
        link:"https://www.youtube.com/watch?v=QNb6S5yYMaM&list=PLF22voURaQgfrVZUr75Z_dHnwbR1S0xln&index=2",
        deadline: "2021-11-30",
        img:"../img/searchIcon.svg",
        members:["user1","user2",],
        done:2,
 
    },
    
];
export const CostomUser=[
    {
        email:"gyuhoWang1@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },
    {
        email:"gyuhoWang2@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },{
        email:"gyuhoWang3@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },{
        email:"gyuhoWang4@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },{
        email:"gyuhoWang5@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },{
        email:"gyuhoWang6@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },{
        email:"gyuhoWang7@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },{
        email:"gyuhoWang8@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },{
        email:"gyuhoWang9@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },{
        email:"gyuhoWang10@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },{
        email:"gyuhoWang11@naver.com",
        password:"abcd",
        nickname:"왕만두",
        address:"마포구 공덕동",
        profile_image:"",
    },
]